# Generated by Django 5.2.6 on 2025-09-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('asiste', models.IntegerField()),
                ('comentarios_ses', models.TextField(blank=True, null=True)),
                ('hora_inicio_ses', models.TimeField(blank=True, null=True)),
                ('hora_termino_ses', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sesion',
                'managed': False,
            },
        ),
    ]
