# Generated by Django 5.2.6 on 2025-09-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canino',
            fields=[
                ('id_canino', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_can', models.CharField(max_length=20)),
                ('edad_can', models.IntegerField()),
                ('raza_can', models.CharField(max_length=15)),
                ('peso_can', models.IntegerField()),
                ('tamano_can', models.CharField(max_length=10)),
                ('cuidados_esp_can', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'canino',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_cli', models.CharField(max_length=30)),
                ('apellidos_cli', models.CharField(max_length=30)),
                ('email_cli', models.CharField(max_length=70)),
                ('numero_cli', models.IntegerField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('servicio_res', models.CharField(max_length=20)),
                ('hora_res', models.TimeField()),
                ('fecha_res', models.DateField()),
                ('medio_pago_res', models.CharField(max_length=15)),
                ('valor_res', models.IntegerField()),
                ('confirm_pago_res', models.IntegerField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
    ]
