# Generated by Django 5.2.6 on 2025-10-28 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('asiste', models.BooleanField(verbose_name='Asiste')),
                ('cont_aviso_retiro_ses', models.PositiveIntegerField(verbose_name='Contador de avisos para retiro.')),
                ('conf_aviso_retiro_ses', models.BooleanField(verbose_name='Confirmación recibo de aviso para retiro')),
                ('comentarios_ses', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('hora_inicio_ses', models.TimeField(blank=True, null=True, verbose_name='Hora inicio sesión')),
                ('hora_termino_ses', models.TimeField(blank=True, null=True, verbose_name='Hora termino sesión')),
                ('canino_id_ses', models.ForeignKey(db_column='canino_id_ses', on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='reservas.canino', verbose_name='Canino')),
                ('reserva_id_ses', models.OneToOneField(db_column='reserva_id_ses', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Sesion',
                'verbose_name_plural': 'Sesiones',
                'db_table': 'sesion',
            },
        ),
    ]
