# Generated by Django 5.2.6 on 2025-10-28 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_cli', models.CharField(max_length=30, verbose_name='Nombre/s')),
                ('apellidos_cli', models.CharField(max_length=30, verbose_name='Apellido/s')),
                ('email_cli', models.EmailField(max_length=70, unique=True, verbose_name='Correo electrónico')),
                ('numero_cli', models.CharField(max_length=12, unique=True, verbose_name='Número de contacto')),
                ('password_cli', models.CharField(max_length=128, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Canino',
            fields=[
                ('id_canino', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_can', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('fecha_nac_can', models.DateField(verbose_name='Fecha de nacimiento')),
                ('raza_can', models.CharField(max_length=15, verbose_name='Raza')),
                ('peso_can', models.PositiveIntegerField(verbose_name='Peso (kg)')),
                ('tamano_can', models.CharField(choices=[('', 'Seleccione tamaño'), ('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10, verbose_name='Tamaño')),
                ('cuidados_esp_can', models.TextField(blank=True, null=True, verbose_name='Cuidados especiales')),
                ('eliminado_can', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('cliente_id_can', models.ForeignKey(db_column='cliente_id_can', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='caninos', to='reservas.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Canino',
                'verbose_name_plural': 'Caninos',
                'db_table': 'canino',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('servicio_res', models.CharField(max_length=20, verbose_name='Servicio')),
                ('hora_res', models.TimeField(verbose_name='Hora')),
                ('fecha_res', models.DateField(verbose_name='Fecha')),
                ('medio_pago_res', models.CharField(max_length=15, verbose_name='Medio de pago')),
                ('valor_res', models.PositiveIntegerField(verbose_name='Valor')),
                ('confirm_pago_res', models.BooleanField(default=False, verbose_name='Pago confirmado')),
                ('canino_id_res', models.ForeignKey(db_column='canino_id_res', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.canino', verbose_name='Canino')),
                ('cliente_id_res', models.ForeignKey(db_column='cliente_id_res', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
    ]
