# Generated by Django 5.2.6 on 2025-11-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('fecha_res', 'hora_res'), name='unique_fecha_hora'),
        ),
    ]
