# Generated by Django 5.2.6 on 2025-11-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_unique_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='servicio_res',
            field=models.CharField(max_length=30, verbose_name='Servicio'),
        ),
    ]
