# Generated by Django 5.2.6 on 2025-11-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_servicio_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Es dueño'),
        ),
    ]
