# Generated by Django 5.2.6 on 2025-11-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_cliente_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='Correo verificado'),
        ),
    ]
