# Generated by Django 5.2.6 on 2025-11-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_cliente_email_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='servicio_res',
            field=models.CharField(max_length=255, verbose_name='Servicio'),
        ),
    ]
