# Generated by Django 5.2.6 on 2025-12-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_reserva_servicio_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canino',
            name='raza_can',
            field=models.CharField(max_length=30, verbose_name='Raza'),
        ),
    ]
