# Generated by Django 5.2.6 on 2025-12-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_canino_raza_can'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='abono',
            field=models.BooleanField(default=False, verbose_name='Abono'),
        ),
    ]
