# Generated by Django 5.2.6 on 2025-12-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_reserva_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='verificando',
            field=models.BooleanField(default=False, verbose_name='Verificando transferencia'),
        ),
    ]
