# Generated by Django 5.2.6 on 2025-12-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_reserva_verificando'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='idPago',
            field=models.CharField(max_length=100, null=True, verbose_name='ID pago vía khipu'),
        ),
    ]
