# Generated by Django 5.2.6 on 2025-12-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_reserva_idpago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='medio_pago_res',
            field=models.CharField(max_length=17, verbose_name='Medio de pago'),
        ),
    ]
